### ISSUE TITLE
Email templates legacy after Magento 2.4.0

### ISSUE THREAD

**Issue by anvanza** [creative-ict/sendcloud#106]
**Description**
The email templates included in the module are no longer working after 2.4.0.

**How to reproduce**
- Start a 2.4.1 environment
- Create a new email template from "New Order" (which is now overridden by SendCloud)
- Create order and send mail.
- The mail sent will not contain all variables like it should.

**Problem**
Magento made some changes to the variables in Email templates
https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/templates/template-email-migration.html

**Solution**
Remove the email templates in this code base so the normal templates are loaded.
And create a documentation for the admin to add the servicepoint part in manually.

--or--

Correct the templates but lose backward compatibility

-- or --

Tell users to add the is_lagacy flag in the "email_template" table.
(not my favorite solution)

**Comment by aderik** [comment]
This is fixed in #113
