### ISSUE TITLE
Salable quantity issues with Magento 2.3.6-p1

### ISSUE THREAD

**Issue by dragonfly4** [creative-ict/sendcloud#115]
Magento 2.3.6-p1
Sendcloud: 1.7.1
PHP: 7.3.27
CentOS Linux release 7.9.2009 (Core)
Apache: 2.4.6

We have been having issues with the quantity and salable quantity numbers for months. Unable to find the cause and even suspecting theft in the warehouse. To get a grip of the situation we have installed the BSS Inventory Report Module

https://bsscommerce.com/magento-2-inventory-report-extension.html

This shows some weird changes executed by the "Rest API Source". Checking the logs it comes from Sendcloud. Below are 2 records for 2 different orders.

### Order #1020211058 for one item

Magento lowers the salable quantity with -1 for the order.
Sendcloud changes the quantity with -1 but does +1 salable quantity number.

`[19/Mar/2021:14:56:23 +0100] 52.29.84.45 TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384 "SendCloud/1.0 (magento_v2; https://www.sendcloud.sc)" "POST /index.php/rest/V1/order/55701/ship HTTP/1.1" 200 27`

![sendcloud-order-001](https://user-images.githubusercontent.com/221351/112000770-93ce9080-8b1e-11eb-8dfd-123207808efb.jpg)

### Order #1020211094 for 4 items

Magento lowers the salable quantity with -4 for the order.
Sendcloud changes the quantity with -4 but does -3 salable quantity number.

`[19/Mar/2021:16:42:16 +0100] 52.29.84.45 TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384 "SendCloud/1.0 (magento_v2; https://www.sendcloud.sc)" "POST /index.php/rest/V1/order/55737/ship HTTP/1.1" 200 27`

![sendcloud-order-002](https://user-images.githubusercontent.com/221351/112001597-67ffda80-8b1f-11eb-8f2e-4f479344b65a.jpg)

If Sendcloud creates a shipment is it then triggering internal Magento webbooks or does it change the quantity itself?

Is this behaviour you have seen before please?

**Comment by aderik** [comment]
Hi,

No. Only the internal webhook. 
But SendCloud do confirm the order items with the quantities.

Like this with json:
POST /index.php/rest/V1/order/18/ship

Content:

{"entity":{"order_id":"18","items":[{"order_item_id":27,"qty":1}]}}

Could you check in your case if the quantities in the json differs from the order?

You can install a api logger to check this: https://github.com/vladflonta/magento2-webapi-log

**Comment by dragonfly4** [comment]
Very well, I have installed a module so will let it run for 24 hours.

https://github.com/magestat/magento2-log-webapi

**Comment by dragonfly4** [comment]
Can I enable debugging for that web hook you are calling please? Currently running v1.8.0

After each Sendcloud shipment I see it adds the ordered quantity to the salable quantity. So we have massive issues with products that were sold but cannot be shipped as the physical stock is lower.

Example of your api call log

`[2021/03/23 09:08:54] {
    "REQUEST:": {
        "method": "POST",
        "uri": "\/index.php\/rest\/V1\/order\/55805\/ship",
        "headers": {
            "Authorization": "Bearer ***********",
            "Host": "*******",
            "User-Agent": "SendCloud\/1.0 (magento_v2; https:\/\/www.sendcloud.sc)",
            "Accept-Encoding": "gzip, deflate",
            "Accept": "*\/*",
            "Connection": "keep-alive",
            "Content-Type": "application\/json",
            "Cache-Control": "no-cache",
            "Content-Length": "206"
        },
        "body": {
            "entity": {
                "order_id": "55805",
                "items": [
                    {
                        "order_item_id": 258788,
                        "qty": 1
                    },
                    {
                        "order_item_id": 258789,
                        "qty": 1
                    },
                    {
                        "order_item_id": 258790,
                        "qty": 1
                    },
                    {
                        "order_item_id": 258791,
                        "qty": 1
                    },
                    {
                        "order_item_id": 258792,
                        "qty": 1
                    }
                ]
            }
        }
    },
    "RESPONSE:": "52785"
`

**Comment by aderik** [comment]
If the order items and quantities are correct we cannot help you. Because this is the way to create an shipment in Magento2. 
See https://devdocs.magento.com/guides/v2.4/rest/tutorials/orders/order-create-shipment.html. The only difference is we not only set the order id in the url but also in the body of the message.
