### ISSUE TITLE
can't install release 1.0.11 on a fresh magento 2.3.1

### ISSUE THREAD

**Issue by Issam7** [creative-ict/sendcloud#15]
Hello,

I'm facing an issue on trying to install release 1.0.11 on a fresh magento 2.3.1
Here is the output:

> $ composer require sendcloud/sendcloud

>Using version ^1.0 for sendcloud/sendcloud
>./composer.json has been updated
>Loading composer repositories with package information
>Updating dependencies (including require-dev)
>Your requirements could not be resolved to an installable set of packages.
>
>  Problem 1
>    - Installation request for sendcloud/sendcloud ^1.0 -> satisfiable by >sendcloud/sendcloud[1.0.10, 1.0.11, 1.0.6, 1.0.7, 1.0.8, 1.0.9].
>    - Can only install one of: magento/framework[102.0.0, 102.0.1].
>    - Can only install one of: magento/framework[102.0.1, 102.0.0].
>    - Can only install one of: magento/framework[102.0.1, 102.0.0].
>    - Conclusion: install magento/framework 102.0.0
>    - Installation request for magento/framework (locked at 102.0.1) -> satisfiable by magento/framework[102.0.1].

**Comment by pimkorschnercreative** [comment]
Hi, 
Thanks for creating the issue, this has been fixed in release 1.0.12
