### ISSUE TITLE
Sendcloud/Block/Checkout/Config $scopeConfig not found

### ISSUE THREAD

**Issue by skast96** [creative-ict/sendcloud#24]
There is an issue within the Config block because you missed an _ it should be 
`
     return $this->_scopeConfig->getValue('sendcloud/sendcloud/script_url', ScopeInterface::SCOPE_STORE);
`

**Comment by digikeijs** [comment]
Change row 26 to 

return $this->_scopeConfig->getValue('sendcloud/sendcloud/script_url', ScopeInterface::SCOPE_STORE);

vendor/sendcloud/sendcloud/Block/Checkout/Config.php

**Comment by pimkorschnercreative** [comment]
Issue has been forwarded to support

**Comment by pointia** [comment]
Already handled in #22 
@pimkorschnercreative please merge the pull request and create new release

**Comment by pimkorschnercreative** [comment]
#22 has been assigned

**Comment by aderik** [comment]
This will be fixed in 1.0.15
