### ISSUE TITLE
First load default onestepcheckout shows service point while country disabled

### ISSUE THREAD

**Issue by digikeijs** [creative-ict/sendcloud#26]
For one of our store views the default country is Germany, on the first load it shows the pickup points method which is not correct. Germany is disabled in the backend. When entering an address the method is disabled but it should check the country on the first load. Magento 2.3.0 with the default magento checkout

![image](https://user-images.githubusercontent.com/34745091/61933620-98782580-af86-11e9-8658-83d94e5ca00e.png)

**Comment by aderik** [comment]
Sorry. I cannot reproduce this.
![afbeelding](https://user-images.githubusercontent.com/614292/74842574-ee4d5a00-532a-11ea-9132-cf57effb2e35.png)

**Comment by aderik** [comment]
Sorry. I cannot reproduce this.
![afbeelding](https://user-images.githubusercontent.com/614292/74842574-ee4d5a00-532a-11ea-9132-cf57effb2e35.png)
But if you use multiple stores you only can set this on website level.
