### ISSUE TITLE
Import Magento shipments and process

### ISSUE THREAD

**Issue by jorgb90** [creative-ict/sendcloud#44]
It would be great if Sendcloud would not only send out T&T e-mails for shipments created within Sendcloud itself, but also for shipments created in Magento. The reason for that is that we do not ship all orders ourselves and thus import shipments for those external orders directly into Magento. It should be easy to implement by importing the tracking code from Magento into Sendcloud and use that code for the updates. Then all T&T e-mails would go through the Sendcloud system.

**Comment by aderik** [comment]
The API of Sendcloud doesn't support this, so it is impossible to implement this in our module.
