### ISSUE TITLE
Using SendCloud in a development environment

### ISSUE THREAD

**Issue by gjportegies** [creative-ict/sendcloud#46]
Is it possible to use / test the SendCloud module in a development environment? I've installed the module via composer and enabled it.

But to use the module I've to connect it to SendCloud, which of course will not work because I'm running with Valet+ on a .test domain.

![Schermafbeelding 2019-11-23 om 14 27 43](https://user-images.githubusercontent.com/6707410/69479478-d6cf0580-0dfd-11ea-8949-a01d65cb8dbc.png)

**Comment by aderik** [comment]
We are using also a docker environment to test the communication between Sendcloud server and our local environment. But we are using ngrok to expose our local environment to the internet.
