### ISSUE TITLE
Support for Amasty Onestepcheckout

### ISSUE THREAD

**Issue by onepack** [creative-ict/sendcloud#47]
One of the biggest providers of Magento modules Amasty is currently not supported.
I tried enabling their Onestepcheckout module but the Sending options are not loaded due to js errors.

I will look into this issue as well.

**Comment by onepack** [comment]
In the source I can see that there have been modifications to work with Amasty OSC.

**Comment by aderik** [comment]
Hi @onepack I can confirm this with version 2.9.0 and higher. So. The Sendcloud module is supported and working with 2.8.5 and lower. Right now we are working for a solution. But I suggest right now to install Amasty One Step Checkout 2.8.5.

**Comment by onepack** [comment]
It would mean I need to go back 8 versions of their module and 23 fixes. I will work on this today.

**Comment by onepack** [comment]
As the older version has issues with our current Magento version we cannot role back this far.
I have contacted Amasty about this issue and they claim this can be solved by them with some customization in their module that will be available for all customers. But this comes with a price.

**Comment by aderik** [comment]
PR #52 is waiting for review

**Comment by aderik** [comment]
This will be solved in release 1.0.18

**Comment by barryvdh** [comment]
I think there are still issues with the latest Amasty One Step Checkout (v3.0.9)?

> [2020-11-11 02:46:06] [ERROR] Failed to load the "SendCloud_SendCloud/js/view/checkout/shipping/servicePoint" component.

**Comment by rickvanoosten** [comment]
@barryvdh please create an new issue with SendCloud version and Magento version. This issue is closed
