### ISSUE TITLE
Free shipping treshhold from config values not working (servicepoint)

### ISSUE THREAD

**Issue by albsa** [creative-ict/sendcloud#48]
Free shipping treshhold from given amount is not working.
Free treshhold is set to 50, however, the price still stays and does not lower to 0.
Please check asap.

**Comment by albsa** [comment]
@rickvanoosten please check this guys, it's a very serious issue.

**Comment by Thomas-gt3** [comment]
I have the same problem, this possibility never worked !

**Comment by maxivol** [comment]
Same issue. Please fix asap

**Comment by aderik** [comment]
Did you try version 1.0.16?

**Comment by Thomas-gt3** [comment]
> Did you try version 1.0.16 ?
Yes, I tried with the latest version.

**Comment by aderik** [comment]
Ok. we will pick this up this week.

**Comment by aderik** [comment]
This is fixed in release 1.0.18
