### ISSUE TITLE
Selecting service point in the Amasty OSC end up as DPD Home - DPD International

### ISSUE THREAD

**Issue by onepack** [creative-ict/sendcloud#56]
I updated the Sendcloud module with the latest changes and found out in two test-orders the service-point selection did not make it to the final order.
DPD Home - DPD International was shown as the selected shipment method what is incorrect as I selected Service point.
I will disable the Amasty checkout and test again if it's also broken in the Magento default checkout.

**Comment by onepack** [comment]
Default Magento checkout is working with this Sendcloud version. So there is still a bug between both modules.

**Comment by aderik** [comment]
Which version SendCloud module and Amasty OSC?

**Comment by Ellen-RoseVD** [comment]
@onepack Which version of Magento, Sendcloud and Amasty OSC do you use?

**Comment by onepack** [comment]
Latest of all:
Magento 2.3.4
Latest Sendcloud via https://github.com/creative-ict/sendcloud with the latest fix to work with the Amasty OSC version 2.11.0

**Comment by rickvanoosten** [comment]
@onepack could you try it with the SendCloud version 1.1.1

**Comment by rickvanoosten** [comment]
closed because it is inactive
