### ISSUE TITLE
Error occurred during "sendcloud_service_point_id" processing. The "" value's type is invalid. The "int" type was expected.

### ISSUE THREAD

**Issue by bamboekeizer** [creative-ict/sendcloud#61]
Sendcloud version 1.0.19
Magento version 2.3.3 (applied composer update) to apply latest updates
Also occurs on Magento version 2.3.4 . Upgraded from 2.3.3

Sendcloud service points disabled.
Integration with sendcloud account is established.

User selects a few products and moves to checkout page (onestepcheckout). After filling in de checkout details and standard delivery, the user hits the order button. 

Expected behaviour:
Order created

Actual behaviour
The order is not created
Briefly an error message appears containing the text "Error occurred during "sendcloud_service_point_id" processing. The "" value's type is invalid. The "int" type was expected."
Then the error message disappears.

**Comment by aderik** [comment]
Which onestepcheckout do you use?

**Comment by bamboekeizer** [comment]
Mageplaza

**Comment by bamboekeizer** [comment]
I installed version 1.0.20 but the same error occurs

**Comment by aderik** [comment]
Can you contact Sendcloud Support?
