### ISSUE TITLE
Some servicepoints are not selectable

### ISSUE THREAD

**Issue by onepack** [creative-ict/sendcloud#70]
When the servicepoint has a lot of timeslots in the time table the "select" button is pushed under the fold. 
As you cannot make the window smaller this pickup-point becomes unavailable to be selected.
See screenprint
![pickup-point-select](https://user-images.githubusercontent.com/475598/77409273-3b549e00-6db9-11ea-88b7-9bdf6e9c7904.png)

It happens with quite some pickuppoints.

**Comment by rickvanoosten** [comment]
@onepack SendCloud is currently working on this bug. This is not related to the SendCloud Magento 2 module but on the servicepoint api. This would be updated on their site so you don't have to update the SendCloud Magento 2 module.
