### ISSUE TITLE
Release 1.0.8 doesn't support Magento 2.3

### ISSUE THREAD

**Issue by nobodyMO** [creative-ict/sendcloud#8]
The current requirements prevents the installation on Magento 2.3
("magento/framework": ">=100 <102")
Please change the  composer.json file.

**Comment by digikeijs** [comment]
@pimkorschner @creative-ict-projecten can you share any timelines on when this will be available for magento 2.3?

**Comment by clatlas127** [comment]
@digikeijs I contacted Sendcloud about this and they told me they expect it to be ready at the end of Q1 or early Q2...

**Comment by albsa** [comment]
Ridiculous, 2.3 has been out now for a while. Even stranger is that you are unable to connect SendCloud without this module.

**Comment by clatlas127** [comment]
@albsa Exactly, 2.3 has been out since the end of November 2018 and yet no solution..Besides what worries me most is that theres absolutely no communication from CreativeICT @creative-ict-projecten, that is absolutely unacceptable from a company like SendCloud..Maybe it's time for SendCloud to hire another company for this job?

**Comment by albsa** [comment]
> @albsa Exactly, 2.3 has been out since the end of November 2018 and yet no solution..Besides what worries me most is that theres absolutely no communication from CreativeICT @creative-ict-projecten, that is absolutely unacceptable from a company like SendCloud..Maybe it's time for SendCloud to hire another company for this job?

I agree on that, also I don't understand why there is not even a single communication about that, even not from SendCloud, I will try to contact them and see what's going on.

**Comment by aderik** [comment]
Solved in 1.0.10

**Comment by Issam7** [comment]
@aderik 
Can you inform us when this will be released as a stable version ?

**Comment by pimkorschnercreative** [comment]
@Issam7 Released as stable in 1.0.11
