### ISSUE TITLE
Shipment templates throwing php errors 2.3.5

### ISSUE THREAD

**Issue by matthew99** [creative-ict/sendcloud#86]
Uncaught Error: Call to a member function getShippingAddress() on...

I think functions are no longer allowed in email templates > 2.3

**Comment by aderik** [comment]
Please. Specify which SendCloud version?
This is already fixed in latest version.

**Comment by matthew99** [comment]
I have version 1.1.2. My client uses Owebia in combination, I think something went wrong in the config there.

**Comment by aderik** [comment]
Please make contact with SendCloud support so we can help you debug your site.
