### ISSUE TITLE
Orders sent to SendCloud based on Order Attribute

### ISSUE THREAD

**Issue by MobiphoneNL** [creative-ict/sendcloud#91]
Hi all,

Currently all our orders are sent from Magento 2 to the SendCloud Dashboard. However we would like to have the ability to specify which orders should be sent to SendCloud and which ones should not be sent to SendCloud, based on for example an order attribute. We were wondering whether a feature like this is on your roadmap?

**Comment by aderik** [comment]
Did you ask SendCloud support for this feature?
